FROM public.ecr.aws/docker/library/python:3.13-slim

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

# CMD ["opentelemetry-instrument", "python", "ecs_main.py"]
RUN chmod +x ecs_bootstrap.sh

CMD ["./ecs_bootstrap.sh"]
